// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYKoDncAcuRph5tck-lEb6tCDQslDM41A',
    appId: '1:867150644744:web:265479d2bb436bf54373bd',
    messagingSenderId: '867150644744',
    projectId: 'throwback-724c9',
    authDomain: 'throwback-724c9.firebaseapp.com',
    storageBucket: 'throwback-724c9.firebasestorage.app',
    measurementId: 'G-0TQW8YE9H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCobw5fPsKkSdfoW1PeL1omDcAQfl9AGy0',
    appId: '1:867150644744:android:a6538846bf8c47d34373bd',
    messagingSenderId: '867150644744',
    projectId: 'throwback-724c9',
    storageBucket: 'throwback-724c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe3YU66dy3Ow-eAe3oYb6U9aa9vYNlyVU',
    appId: '1:867150644744:ios:edc5da18d36bcad84373bd',
    messagingSenderId: '867150644744',
    projectId: 'throwback-724c9',
    storageBucket: 'throwback-724c9.firebasestorage.app',
    iosBundleId: 'de.lenamorawietz.throwback',
  );
}
